"""Initial migration

Revision ID: 13088b0b391d
Revises: 
Create Date: 2025-09-16 22:27:37.878699

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '13088b0b391d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
