"""add_delivery_options_and_product_relationships

Revision ID: 94404b2e4890
Revises: 13088b0b391d
Create Date: 2025-09-22 14:52:16.489702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94404b2e4890'
down_revision: Union[str, Sequence[str], None] = '13088b0b391d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speed', sa.Enum('STANDARD', 'EXPRESS', 'NEXT_DAY', 'SAME_DAY', name='deliveryspeed'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('min_order_amount', sa.Float(), nullable=True),
    sa.Column('estimated_days_min', sa.Integer(), nullable=False),
    sa.Column('estimated_days_max', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_options_name'), 'delivery_options', ['name'], unique=False)
    op.create_table('product_delivery_options',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('delivery_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_option_id'], ['delivery_options.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'delivery_option_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_delivery_options')
    op.drop_index(op.f('ix_delivery_options_name'), table_name='delivery_options')
    op.drop_table('delivery_options')
    # ### end Alembic commands ###
